### ISSUE TITLE
Option --supported-dist does not work with opkgc-4.0

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#483]
**Reported by valleegr on 28 Jun 2008 21:29 UTC**
When trying to use opkgc-4.0 on Ubuntu-7.10 (installed via the binary package), i have the following error:

```
$ opkgc --supported-dist
Supported target distributions are:
Traceback (most recent call last):
  File "/usr/local/bin/opkgc", line 141, in <module>
    main()
  File "/usr/local/bin/opkgc", line 108, in main
    distList()
  File "/usr/local/bin/opkgc", line 72, in distList
    for target in eval(compiler).SupportedDist():
AttributeError: class RPMCompiler has no attribute 'SupportedDist'
```

**Comment by dikim33** [comment]
**Comment by valleegr on 4 Dec 2008 07:10 UTC**
Seems to be fixed with 0.4.1 for some reasons.
