### ISSUE TITLE
pvm doesn't build on fc5 x86_64

### ISSUE THREAD

**Issue by dikim33** [oscar-cluster/oscar#27]
**Reported by efocht on 7 May 2006 21:47 UTC**
When building on fc5-x86_64 I get errors:

making in LINUX64/ for LINUX64
make[2]: Entering directory `/usr/src/redhat/BUILD/pvm3/src/LINUX64'
mkdir ../../lib/LINUX64
cc -O -DCLUMP_ALLOC -DSTATISTICS -DTIMESTAMPLOG -DSANITY -I../../include -DARCHCLASS=\"LINUX64\" -DIMA_LINU
X64 -DSYSVSIGNAL -DNOWAIT3 -DRSHCOMMAND=\"/usr/bin/rsh\" -DNEEDENDIAN -DFDSETNOTSTRUCT -DHASERRORVARS -DHAS
STDLIB -DCTIMEISTIMET -DSYSERRISCONST -DNOTMPNAM -DUSESTRERROR -c ../../src/ddpro.c
../../src/ddpro.c: In function 'addhosts':
../../src/ddpro.c:1041: warning: incompatible implicit declaration of built-in function 'strlen'
../../src/ddpro.c:1049: warning: incompatible implicit declaration of built-in function 'strcpy'
../../src/ddpro.c:1049: warning: incompatible implicit declaration of built-in function 'strlen'
../../src/ddpro.c: In function 'exectasks':
../../src/ddpro.c:1484: warning: incompatible implicit declaration of built-in function 'strlen'
../../src/ddpro.c:1485: warning: incompatible implicit declaration of built-in function 'strcpy'
../../src/ddpro.c:1509: warning: cast to pointer from integer of different size
../../src/ddpro.c: In function 'startack':
../../src/ddpro.c:2125: warning: incompatible implicit declaration of built-in function 'strcpy'
../../src/ddpro.c:2125: warning: incompatible implicit declaration of built-in function 'strlen'
../../src/ddpro.c: In function 'dm_taskout':
../../src/ddpro.c:2709: warning: incompatible implicit declaration of built-in function 'strlen'
cc -O -DCLUMP_ALLOC -DSTATISTICS -DTIMESTAMPLOG -DSANITY -I../../include -DARCHCLASS=\"LINUX64\" -DIMA_LINU
X64 -DSYSVSIGNAL -DNOWAIT3 -DRSHCOMMAND=\"/usr/bin/rsh\" -DNEEDENDIAN -DFDSETNOTSTRUCT -DHASERRORVARS -DHAS
STDLIB -DCTIMEISTIMET -DSYSERRISCONST -DNOTMPNAM -DUSESTRERROR -c ../../src/host.c
In file included from ../../src/host.c:227:
../../src/global.h:321: error: array type has incomplete element type
../../src/global.h:323: error: array type has incomplete element type
../../src/host.c: In function 'ht_insert':
../../src/host.c:536: warning: incompatible implicit declaration of built-in function 'strcpy'
../../src/host.c:536: warning: incompatible implicit declaration of built-in function 'strlen'
...

**Comment by dikim33** [comment]
**Comment by bli on 7 May 2006 22:34 UTC**
A potential fix has been checked into r4729.  Will let Erich confirm before closing.

**Comment by dikim33** [comment]
**Comment by naughtont on 31 May 2006 15:54 UTC**
It appears that the problem on FC5 was a missing include, that Bernard appears to have snagged a fix for from the FC5 SRPMS for pvm.  


FILE: pvm3/src/global.h 
 
MISSING: #include <pvmtev.h>


I'm not sure if this still breaks on x86_64, b/c I don't have a fc5-x86_64 system currently.  I'll continue in that direction soon.

**Comment by dikim33** [comment]
**Comment by naughtont on 31 May 2006 19:18 UTC**
I have tested with fc5-x86 with and without the patch to the 'global.h' file and it build fine.

I do not have access currently to an fc5-x86_64 box so, i'm not sure how to proceed on that front.  The latest pvm I'm testing (3.4.5+6) worked on the CentOS 4.1 x86_64 box I have at ORNL.

So I'll check that SRPM and go from there.

**Comment by dikim33** [comment]
**Comment by naughtont on 31 May 2006 19:29 UTC**
I'm going to checkin the updated SRPM (pvm-3.4.5+6-1.src.rpm) that include the one line patch on the global.h file for a header include.

I'm going to ask erich to try this on his fc5-x86_64 and if that works we can move to this updated version of PVM, otherwise I'll continue to look at this bug (and bug #5).

**Comment by dikim33** [comment]
**Comment by efocht on 1 Jun 2006 08:44 UTC**
The latest PVM builds on fc5-x86_64, I checked it in.
Guess this means the bug is fixed now.

Thanks!
Erich

**Comment by dikim33** [comment]
**Comment by naughtont on 2 Jun 2006 18:07 UTC**
Closing based on Erich's comment.
